---
booktitle: Proceedings of the Second Workshop on Applications of Pattern Analysis
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: JMLR Workshop and Conference Proceedings
month: 0
logo: logo.png
volume: 17
year: '2011'
start: 2011-10-19
end: 2011-10-21
published: 2011-10-21
shortname: 2nd Workshop on Applications of Pattern Analysis
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: WAPA2011
cycles: false
editor:
- given: Tom
  family: Diethe
- given: Jose
  family: Balcazar
- given: John
  family: Shawe-Taylor
- given: Cristina
  family: Tirnauca
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Second Workshop on Applications of Pattern Analysis
    Held in CIEM, Castro Urdiales, Spain on 19-21 October 2011

  Published as Volume 17 by the Proceedings of Machine Learning Research on 21 October 2011.

  Volume Edited by:
    Tom Diethe
    Jose Balcazar
    John Shawe-Taylor
    Cristina Tirnauca

  Series Editors:
    Neil D. Lawrence
date_str: 19--21 Oct
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v17"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v17
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of the Second Workshop on Applications of Pattern Analysis
  url: 
  location: CIEM, Castro Urdiales, Spain
  dates:
  - 2011-10-19
  - 2011-10-20
  - 2011-10-21
  number: 2
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
