---
booktitle: Proceedings of the Second Workshop on Applications of Pattern Analysis
publisher: JMLR Workshop and Conference Proceedings
month: 0
logoright: basic_files/logo.png
volume: 17
year: '2011'
start: 2011-10-19
end: 2011-10-21
published: 2011-10-21
shortname: 2nd Workshop on Applications of Pattern Analysis
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: FIXME-YYYY
abstract: ''
editor:
- given: Tom
  family: Diethe
- given: Jose
  family: Balcazar
- given: John
  family: Shawe-Taylor
- given: Cristina
  family: Tirnauca
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Second Workshop on Applications of Pattern Analysis
    Held in CIEM, Castro Urdiales, Spain on 19-21 October 2011

  Published as Volume 17 by the Proceedings of Machine Learning Research on 21 October 2011.

  Volume Edited by:
    Tom Diethe
    Jose Balcazar
    John Shawe-Taylor
    Cristina Tirnauca

  Series Editors:
    Neil D. Lawrence
url: http://proceedings.mlr.press
baseurl: "/v17"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v17
email: ''
conference:
  name: Proceedings of the Second Workshop on Applications of Pattern Analysis
  url: 
  location: CIEM, Castro Urdiales, Spain
  dates:
  - 2011-10-19
  - 2011-10-20
  - 2011-10-21
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v17.bib
